#!/usr/bin/ruby

global_name = `git config --get user.name`.gsub("\n", '')
global_email = `git config --get user.email`.gsub("\n", '')

user_name = "Mannie Tagarira"
email = "mannie@dimensionsunmarked.com"

`git config --global user.name '#{user_name}'` unless global_name==user_name
`git config --global user.email #{email}` unless global_email==email

`git init`
